services:
  - type: web
    name: myfuelforce
    runtime: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "4320"
      - key: CORS_ORIGINS
        value: "*"
      - key: DATABASE_URL
        sync: false
